name: Autograding
on: [push]
jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Autograding Tests
        run: npm test

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        if: always()
